const dotenv = require("dotenv")
dotenv.config()

const {
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_HOST,
  DATABASE_NAME,
  DATABASE_DIALECT,
  PORT,
  ACCESS_SECRET, REFRESH_SECRET
} = process.env

module.exports = {
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_HOST,
  DATABASE_NAME,
  PORT,
  DATABASE_DIALECT,
  ACCESS_SECRET, REFRESH_SECRET
}
